%{?!ros_distro:%global ros_distro lyrical}
%global pkg_name ehukai
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-lyrical-ehukai
Version:        0.0.3
Release:        1%{?dist}
Summary:        ROS %{pkg_name} package

License:        Apache-2.0
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  cmake

%{?bloom_package}

%description
Headless spectral ocean-wave synthesis library: TMA/JONSWAP/Pierson-Moskowitz
spectra with directional spreading and dispersion, after Horvath (2015). Exports
the ehukai::ehukai CMake target. This manifest exists so the library can be
developed as a peer of its consumers in a colcon workspace. It is a plain CMake
package — colcon does not change how it is configured, built or installed, and
it is not a ROS package in any other sense. The Debian packaging
(cmake/Packaging.cmake) and a standalone cmake build are unaffected.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
Headless spectral ocean-wave synthesis library: TMA/JONSWAP/Pierson-Moskowitz
spectra with directional spreading and dispersion, after Horvath (2015). Exports
the ehukai::ehukai CMake target. This manifest exists so the library can be
developed as a peer of its consumers in a colcon workspace. It is a plain CMake
package — colcon does not change how it is configured, built or installed, and
it is not a ROS package in any other sense. The Debian packaging
(cmake/Packaging.cmake) and a standalone cmake build are unaffected.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
Headless spectral ocean-wave synthesis library: TMA/JONSWAP/Pierson-Moskowitz
spectra with directional spreading and dispersion, after Horvath (2015). Exports
the ehukai::ehukai CMake target. This manifest exists so the library can be
developed as a peer of its consumers in a colcon workspace. It is a plain CMake
package — colcon does not change how it is configured, built or installed, and
it is not a ROS package in any other sense. The Debian packaging
(cmake/Packaging.cmake) and a standalone cmake build are unaffected.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%cmake \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="%{bloom_prefix}" \
    -DCMAKE_PREFIX_PATH="%{bloom_prefix}" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif

%cmake3_build


%install
%cmake_install


%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C %{__cmake_builddir} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
CTEST_OUTPUT_ON_FAILURE=1 \
    %cmake_build $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%license LICENSE
%{bloom_prefix}


%changelog
* Thu Oct 01 2026 Honu Robotics <info@honurobotics.com> - 0.0.3-1
- Autogenerated by Bloom
